export * from "./structs.ts";

// Autogenerated API file for SchedulingV1alpha1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as SchedulingV1alpha1 from "./structs.ts";

export class SchedulingV1alpha1Api {
  #client: c.RestClient;
  #root = "/apis/scheduling.k8s.io/v1alpha1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  namespace(name: string): SchedulingV1alpha1NamespacedApi {
    return new SchedulingV1alpha1NamespacedApi(this.#client, name);
  }
  myNamespace(): SchedulingV1alpha1NamespacedApi {
    if (!this.#client.defaultNamespace) throw new Error("No current namespace is set");
    return new SchedulingV1alpha1NamespacedApi(this.#client, this.#client.defaultNamespace);
  }

  async getWorkloadListForAllNamespaces(
    opts: operations.GetListOpts = {},
  ): Promise<SchedulingV1alpha1.WorkloadList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}workloads`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkloadList(resp);
  }

  async watchWorkloadListForAllNamespaces(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<SchedulingV1alpha1.Workload>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}workloads`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(SchedulingV1alpha1.toWorkload, MetaV1.toStatus));
  }

}

export class SchedulingV1alpha1NamespacedApi {
  #client: c.RestClient
  #root: string
  constructor(client: c.RestClient, namespace: string) {
    this.#client = client;
    this.#root = `/apis/scheduling.k8s.io/v1alpha1/namespaces/${namespace}/`;
  }

  async getWorkloadList(
    opts: operations.GetListOpts = {},
  ): Promise<SchedulingV1alpha1.WorkloadList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}workloads`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkloadList(resp);
  }

  async watchWorkloadList(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<SchedulingV1alpha1.Workload>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}workloads`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(SchedulingV1alpha1.toWorkload, MetaV1.toStatus));
  }

  async createWorkload(
    body: SchedulingV1alpha1.Workload,
    opts: operations.PutOpts = {},
  ): Promise<SchedulingV1alpha1.Workload> {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}workloads`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: SchedulingV1alpha1.fromWorkload(body),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkload(resp);
  }

  async deleteWorkloadList(
    opts: operations.DeleteListOpts = {},
  ): Promise<SchedulingV1alpha1.WorkloadList> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}workloads`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkloadList(resp);
  }

  async getWorkload(
    name: string,
    opts: operations.NoOpts = {},
  ): Promise<SchedulingV1alpha1.Workload> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}workloads/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkload(resp);
  }

  async deleteWorkload(
    name: string,
    opts: operations.DeleteOpts = {},
  ): Promise<SchedulingV1alpha1.Workload | MetaV1.Status> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}workloads/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return SchedulingV1alpha1.toWorkload(resp);
  }

  async replaceWorkload(
    name: string,
    body: SchedulingV1alpha1.Workload,
    opts: operations.PutOpts = {},
  ): Promise<SchedulingV1alpha1.Workload> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}workloads/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: SchedulingV1alpha1.fromWorkload(body),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkload(resp);
  }

  async patchWorkload(
    name: string,
    type: c.PatchType,
    body: SchedulingV1alpha1.Workload | c.JsonPatch,
    opts: operations.PatchOpts = {},
  ): Promise<SchedulingV1alpha1.Workload> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}workloads/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : SchedulingV1alpha1.fromWorkload(body),
      abortSignal: opts.abortSignal,
    });
    return SchedulingV1alpha1.toWorkload(resp);
  }

}
