// Autogenerated Schema file for SchedulingV1alpha1
import * as c from "../../common.ts";

import * as MetaV1 from "../meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

/** BasicSchedulingPolicy indicates that standard Kubernetes scheduling behavior should be used. */
export interface BasicSchedulingPolicy {
}
export function toBasicSchedulingPolicy(input: c.JSONValue): BasicSchedulingPolicy {
  const obj = c.checkObj(input);
  return {
  }}
export function fromBasicSchedulingPolicy(input: BasicSchedulingPolicy): c.JSONValue {
  return {
    ...input,
  }}

/** GangSchedulingPolicy defines the parameters for gang scheduling. */
export interface GangSchedulingPolicy {
  minCount: number;
}
export function toGangSchedulingPolicy(input: c.JSONValue): GangSchedulingPolicy {
  const obj = c.checkObj(input);
  return {
    minCount: c.checkNum(obj["minCount"]),
  }}
export function fromGangSchedulingPolicy(input: GangSchedulingPolicy): c.JSONValue {
  return {
    ...input,
  }}

/** PodGroup represents a set of pods with a common scheduling policy. */
export interface PodGroup {
  name: string;
  policy: PodGroupPolicy;
}
export function toPodGroup(input: c.JSONValue): PodGroup {
  const obj = c.checkObj(input);
  return {
    name: c.checkStr(obj["name"]),
    policy: toPodGroupPolicy(obj["policy"]),
  }}
export function fromPodGroup(input: PodGroup): c.JSONValue {
  return {
    ...input,
    policy: input.policy != null ? fromPodGroupPolicy(input.policy) : undefined,
  }}

/** PodGroupPolicy defines the scheduling configuration for a PodGroup. */
export interface PodGroupPolicy {
  basic?: BasicSchedulingPolicy | null;
  gang?: GangSchedulingPolicy | null;
}
export function toPodGroupPolicy(input: c.JSONValue): PodGroupPolicy {
  const obj = c.checkObj(input);
  return {
    basic: c.readOpt(obj["basic"], toBasicSchedulingPolicy),
    gang: c.readOpt(obj["gang"], toGangSchedulingPolicy),
  }}
export function fromPodGroupPolicy(input: PodGroupPolicy): c.JSONValue {
  return {
    ...input,
    basic: input.basic != null ? fromBasicSchedulingPolicy(input.basic) : undefined,
    gang: input.gang != null ? fromGangSchedulingPolicy(input.gang) : undefined,
  }}

/** TypedLocalObjectReference allows to reference typed object inside the same namespace. */
export interface TypedLocalObjectReference {
  apiGroup?: string | null;
  kind: string;
  name: string;
}
export function toTypedLocalObjectReference(input: c.JSONValue): TypedLocalObjectReference {
  const obj = c.checkObj(input);
  return {
    apiGroup: c.readOpt(obj["apiGroup"], c.checkStr),
    kind: c.checkStr(obj["kind"]),
    name: c.checkStr(obj["name"]),
  }}
export function fromTypedLocalObjectReference(input: TypedLocalObjectReference): c.JSONValue {
  return {
    ...input,
  }}

/** Workload allows for expressing scheduling constraints that should be used when managing lifecycle of workloads from scheduling perspective, including scheduling, preemption, eviction and other phases. */
export interface Workload {
  apiVersion?: "scheduling.k8s.io/v1alpha1";
  kind?: "Workload";
  metadata?: MetaV1.ObjectMeta | null;
  spec: WorkloadSpec;
}
export function toWorkload(input: c.JSONValue): Workload & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "scheduling.k8s.io/v1alpha1", "Workload"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: toWorkloadSpec(obj["spec"]),
  }}
export function fromWorkload(input: Workload): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "scheduling.k8s.io/v1alpha1", "Workload"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromWorkloadSpec(input.spec) : undefined,
  }}

/** WorkloadSpec defines the desired state of a Workload. */
export interface WorkloadSpec {
  controllerRef?: TypedLocalObjectReference | null;
  podGroups: Array<PodGroup>;
}
export function toWorkloadSpec(input: c.JSONValue): WorkloadSpec {
  const obj = c.checkObj(input);
  return {
    controllerRef: c.readOpt(obj["controllerRef"], toTypedLocalObjectReference),
    podGroups: c.readList(obj["podGroups"], toPodGroup),
  }}
export function fromWorkloadSpec(input: WorkloadSpec): c.JSONValue {
  return {
    ...input,
    controllerRef: input.controllerRef != null ? fromTypedLocalObjectReference(input.controllerRef) : undefined,
    podGroups: input.podGroups?.map(fromPodGroup),
  }}

/** WorkloadList contains a list of Workload resources. */
export interface WorkloadList extends ListOf<Workload> {
  apiVersion?: "scheduling.k8s.io/v1alpha1";
  kind?: "WorkloadList";
};
export function toWorkloadList(input: c.JSONValue): WorkloadList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "scheduling.k8s.io/v1alpha1", "WorkloadList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toWorkload),
  }}
