export * from "./structs.ts";

// Autogenerated API file for ResourceV1alpha3
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as ResourceV1alpha3 from "./structs.ts";

export class ResourceV1alpha3Api {
  #client: c.RestClient;
  #root = "/apis/resource.k8s.io/v1alpha3/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  async getDeviceTaintRuleList(
    opts: operations.GetListOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRuleList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}devicetaintrules`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRuleList(resp);
  }

  async watchDeviceTaintRuleList(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<ResourceV1alpha3.DeviceTaintRule>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}devicetaintrules`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(ResourceV1alpha3.toDeviceTaintRule, MetaV1.toStatus));
  }

  async createDeviceTaintRule(
    body: ResourceV1alpha3.DeviceTaintRule,
    opts: operations.PutOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}devicetaintrules`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha3.fromDeviceTaintRule(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async deleteDeviceTaintRuleList(
    opts: operations.DeleteListOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRuleList> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}devicetaintrules`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRuleList(resp);
  }

  async getDeviceTaintRule(
    name: string,
    opts: operations.NoOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}devicetaintrules/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async deleteDeviceTaintRule(
    name: string,
    opts: operations.DeleteOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule | MetaV1.Status> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}devicetaintrules/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async replaceDeviceTaintRule(
    name: string,
    body: ResourceV1alpha3.DeviceTaintRule,
    opts: operations.PutOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}devicetaintrules/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha3.fromDeviceTaintRule(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async patchDeviceTaintRule(
    name: string,
    type: c.PatchType,
    body: ResourceV1alpha3.DeviceTaintRule | c.JsonPatch,
    opts: operations.PatchOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}devicetaintrules/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha3.fromDeviceTaintRule(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async getDeviceTaintRuleStatus(
    name: string,
    opts: operations.NoOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}devicetaintrules/${name}/status`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async replaceDeviceTaintRuleStatus(
    name: string,
    body: ResourceV1alpha3.DeviceTaintRule,
    opts: operations.PutOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}devicetaintrules/${name}/status`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: ResourceV1alpha3.fromDeviceTaintRule(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

  async patchDeviceTaintRuleStatus(
    name: string,
    type: c.PatchType,
    body: ResourceV1alpha3.DeviceTaintRule | c.JsonPatch,
    opts: operations.PatchOpts = {},
  ): Promise<ResourceV1alpha3.DeviceTaintRule> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}devicetaintrules/${name}/status`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : ResourceV1alpha3.fromDeviceTaintRule(body),
      abortSignal: opts.abortSignal,
    });
    return ResourceV1alpha3.toDeviceTaintRule(resp);
  }

}
