// Autogenerated Schema file for StoragemigrationV1beta1
import * as c from "../../common.ts";

import * as MetaV1 from "../meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

/** StorageVersionMigration represents a migration of stored data to the latest storage version. */
export interface StorageVersionMigration {
  apiVersion?: "storagemigration.k8s.io/v1beta1";
  kind?: "StorageVersionMigration";
  metadata?: MetaV1.ObjectMeta | null;
  spec?: StorageVersionMigrationSpec | null;
  status?: StorageVersionMigrationStatus | null;
}
export function toStorageVersionMigration(input: c.JSONValue): StorageVersionMigration & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "storagemigration.k8s.io/v1beta1", "StorageVersionMigration"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: c.readOpt(obj["spec"], toStorageVersionMigrationSpec),
    status: c.readOpt(obj["status"], toStorageVersionMigrationStatus),
  }}
export function fromStorageVersionMigration(input: StorageVersionMigration): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "storagemigration.k8s.io/v1beta1", "StorageVersionMigration"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromStorageVersionMigrationSpec(input.spec) : undefined,
    status: input.status != null ? fromStorageVersionMigrationStatus(input.status) : undefined,
  }}

/** Spec of the storage version migration. */
export interface StorageVersionMigrationSpec {
  resource: MetaV1.GroupResource;
}
export function toStorageVersionMigrationSpec(input: c.JSONValue): StorageVersionMigrationSpec {
  const obj = c.checkObj(input);
  return {
    resource: MetaV1.toGroupResource(obj["resource"]),
  }}
export function fromStorageVersionMigrationSpec(input: StorageVersionMigrationSpec): c.JSONValue {
  return {
    ...input,
    resource: input.resource != null ? MetaV1.fromGroupResource(input.resource) : undefined,
  }}

/** Status of the storage version migration. */
export interface StorageVersionMigrationStatus {
  conditions?: Array<MetaV1.Condition> | null;
  resourceVersion?: string | null;
}
export function toStorageVersionMigrationStatus(input: c.JSONValue): StorageVersionMigrationStatus {
  const obj = c.checkObj(input);
  return {
    conditions: c.readOpt(obj["conditions"], x => c.readList(x, MetaV1.toCondition)),
    resourceVersion: c.readOpt(obj["resourceVersion"], c.checkStr),
  }}
export function fromStorageVersionMigrationStatus(input: StorageVersionMigrationStatus): c.JSONValue {
  return {
    ...input,
    conditions: input.conditions?.map(MetaV1.fromCondition),
  }}

/** StorageVersionMigrationList is a collection of storage version migrations. */
export interface StorageVersionMigrationList extends ListOf<StorageVersionMigration> {
  apiVersion?: "storagemigration.k8s.io/v1beta1";
  kind?: "StorageVersionMigrationList";
};
export function toStorageVersionMigrationList(input: c.JSONValue): StorageVersionMigrationList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "storagemigration.k8s.io/v1beta1", "StorageVersionMigrationList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toStorageVersionMigration),
  }}
