export * from "./structs.ts";

// Autogenerated API file for CertificatesV1beta1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as CertificatesV1beta1 from "./structs.ts";

export class CertificatesV1beta1Api {
  #client: c.RestClient;
  #root = "/apis/certificates.k8s.io/v1beta1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  async getClusterTrustBundleList(
    opts: operations.GetListOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundleList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}clustertrustbundles`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundleList(resp);
  }

  async watchClusterTrustBundleList(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<CertificatesV1beta1.ClusterTrustBundle>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}clustertrustbundles`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(CertificatesV1beta1.toClusterTrustBundle, MetaV1.toStatus));
  }

  async createClusterTrustBundle(
    body: CertificatesV1beta1.ClusterTrustBundle,
    opts: operations.PutOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundle> {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}clustertrustbundles`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: CertificatesV1beta1.fromClusterTrustBundle(body),
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundle(resp);
  }

  async deleteClusterTrustBundleList(
    opts: operations.DeleteListOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundleList> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}clustertrustbundles`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundleList(resp);
  }

  async getClusterTrustBundle(
    name: string,
    opts: operations.NoOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundle> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}clustertrustbundles/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundle(resp);
  }

  async deleteClusterTrustBundle(
    name: string,
    opts: operations.DeleteOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundle | MetaV1.Status> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}clustertrustbundles/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return CertificatesV1beta1.toClusterTrustBundle(resp);
  }

  async replaceClusterTrustBundle(
    name: string,
    body: CertificatesV1beta1.ClusterTrustBundle,
    opts: operations.PutOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundle> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}clustertrustbundles/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: CertificatesV1beta1.fromClusterTrustBundle(body),
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundle(resp);
  }

  async patchClusterTrustBundle(
    name: string,
    type: c.PatchType,
    body: CertificatesV1beta1.ClusterTrustBundle | c.JsonPatch,
    opts: operations.PatchOpts = {},
  ): Promise<CertificatesV1beta1.ClusterTrustBundle> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}clustertrustbundles/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : CertificatesV1beta1.fromClusterTrustBundle(body),
      abortSignal: opts.abortSignal,
    });
    return CertificatesV1beta1.toClusterTrustBundle(resp);
  }

}
