// Autogenerated Schema file for CertificatesV1beta1
import * as c from "../../common.ts";

import * as MetaV1 from "../meta@v1/structs.ts";
type ListOf<T> = {
  metadata: MetaV1.ListMeta;
  items: Array<T>;
};

/** ClusterTrustBundle is a cluster-scoped container for X.509 trust anchors (root certificates).

ClusterTrustBundle objects are considered to be readable by any authenticated user in the cluster, because they can be mounted by pods using the `clusterTrustBundle` projection.  All service accounts have read access to ClusterTrustBundles by default.  Users who only have namespace-level access to a cluster can read ClusterTrustBundles by impersonating a serviceaccount that they have access to.

It can be optionally associated with a particular assigner, in which case it contains one valid set of trust anchors for that signer. Signers may have multiple associated ClusterTrustBundles; each is an independent set of trust anchors for that signer. Admission control is used to enforce that only users with permissions on the signer can create or modify the corresponding bundle. */
export interface ClusterTrustBundle {
  apiVersion?: "certificates.k8s.io/v1beta1";
  kind?: "ClusterTrustBundle";
  metadata?: MetaV1.ObjectMeta | null;
  spec: ClusterTrustBundleSpec;
}
export function toClusterTrustBundle(input: c.JSONValue): ClusterTrustBundle & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1beta1", "ClusterTrustBundle"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: toClusterTrustBundleSpec(obj["spec"]),
  }}
export function fromClusterTrustBundle(input: ClusterTrustBundle): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "certificates.k8s.io/v1beta1", "ClusterTrustBundle"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromClusterTrustBundleSpec(input.spec) : undefined,
  }}

/** ClusterTrustBundleSpec contains the signer and trust anchors. */
export interface ClusterTrustBundleSpec {
  signerName?: string | null;
  trustBundle: string;
}
export function toClusterTrustBundleSpec(input: c.JSONValue): ClusterTrustBundleSpec {
  const obj = c.checkObj(input);
  return {
    signerName: c.readOpt(obj["signerName"], c.checkStr),
    trustBundle: c.checkStr(obj["trustBundle"]),
  }}
export function fromClusterTrustBundleSpec(input: ClusterTrustBundleSpec): c.JSONValue {
  return {
    ...input,
  }}

/** ClusterTrustBundleList is a collection of ClusterTrustBundle objects */
export interface ClusterTrustBundleList extends ListOf<ClusterTrustBundle> {
  apiVersion?: "certificates.k8s.io/v1beta1";
  kind?: "ClusterTrustBundleList";
};
export function toClusterTrustBundleList(input: c.JSONValue): ClusterTrustBundleList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1beta1", "ClusterTrustBundleList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toClusterTrustBundle),
  }}

/** PodCertificateRequest encodes a pod requesting a certificate from a given signer.

Kubelets use this API to implement podCertificate projected volumes */
export interface PodCertificateRequest {
  apiVersion?: "certificates.k8s.io/v1beta1";
  kind?: "PodCertificateRequest";
  metadata?: MetaV1.ObjectMeta | null;
  spec: PodCertificateRequestSpec;
  status?: PodCertificateRequestStatus | null;
}
export function toPodCertificateRequest(input: c.JSONValue): PodCertificateRequest & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1beta1", "PodCertificateRequest"),
    metadata: c.readOpt(obj["metadata"], MetaV1.toObjectMeta),
    spec: toPodCertificateRequestSpec(obj["spec"]),
    status: c.readOpt(obj["status"], toPodCertificateRequestStatus),
  }}
export function fromPodCertificateRequest(input: PodCertificateRequest): c.JSONValue {
  return {
    ...c.assertOrAddApiVersionAndKind(input, "certificates.k8s.io/v1beta1", "PodCertificateRequest"),
    ...input,
    metadata: input.metadata != null ? MetaV1.fromObjectMeta(input.metadata) : undefined,
    spec: input.spec != null ? fromPodCertificateRequestSpec(input.spec) : undefined,
    status: input.status != null ? fromPodCertificateRequestStatus(input.status) : undefined,
  }}

/** PodCertificateRequestSpec describes the certificate request.  All fields are immutable after creation. */
export interface PodCertificateRequestSpec {
  maxExpirationSeconds?: number | null;
  nodeName: string;
  nodeUID: string;
  pkixPublicKey: string;
  podName: string;
  podUID: string;
  proofOfPossession: string;
  serviceAccountName: string;
  serviceAccountUID: string;
  signerName: string;
  unverifiedUserAnnotations?: Record<string,string> | null;
}
export function toPodCertificateRequestSpec(input: c.JSONValue): PodCertificateRequestSpec {
  const obj = c.checkObj(input);
  return {
    maxExpirationSeconds: c.readOpt(obj["maxExpirationSeconds"], c.checkNum),
    nodeName: c.checkStr(obj["nodeName"]),
    nodeUID: c.checkStr(obj["nodeUID"]),
    pkixPublicKey: c.checkStr(obj["pkixPublicKey"]),
    podName: c.checkStr(obj["podName"]),
    podUID: c.checkStr(obj["podUID"]),
    proofOfPossession: c.checkStr(obj["proofOfPossession"]),
    serviceAccountName: c.checkStr(obj["serviceAccountName"]),
    serviceAccountUID: c.checkStr(obj["serviceAccountUID"]),
    signerName: c.checkStr(obj["signerName"]),
    unverifiedUserAnnotations: c.readOpt(obj["unverifiedUserAnnotations"], x => c.readMap(x, c.checkStr)),
  }}
export function fromPodCertificateRequestSpec(input: PodCertificateRequestSpec): c.JSONValue {
  return {
    ...input,
  }}

/** PodCertificateRequestStatus describes the status of the request, and holds the certificate data if the request is issued. */
export interface PodCertificateRequestStatus {
  beginRefreshAt?: c.Time | null;
  certificateChain?: string | null;
  conditions?: Array<MetaV1.Condition> | null;
  notAfter?: c.Time | null;
  notBefore?: c.Time | null;
}
export function toPodCertificateRequestStatus(input: c.JSONValue): PodCertificateRequestStatus {
  const obj = c.checkObj(input);
  return {
    beginRefreshAt: c.readOpt(obj["beginRefreshAt"], c.toTime),
    certificateChain: c.readOpt(obj["certificateChain"], c.checkStr),
    conditions: c.readOpt(obj["conditions"], x => c.readList(x, MetaV1.toCondition)),
    notAfter: c.readOpt(obj["notAfter"], c.toTime),
    notBefore: c.readOpt(obj["notBefore"], c.toTime),
  }}
export function fromPodCertificateRequestStatus(input: PodCertificateRequestStatus): c.JSONValue {
  return {
    ...input,
    beginRefreshAt: input.beginRefreshAt != null ? c.fromTime(input.beginRefreshAt) : undefined,
    conditions: input.conditions?.map(MetaV1.fromCondition),
    notAfter: input.notAfter != null ? c.fromTime(input.notAfter) : undefined,
    notBefore: input.notBefore != null ? c.fromTime(input.notBefore) : undefined,
  }}

/** PodCertificateRequestList is a collection of PodCertificateRequest objects */
export interface PodCertificateRequestList extends ListOf<PodCertificateRequest> {
  apiVersion?: "certificates.k8s.io/v1beta1";
  kind?: "PodCertificateRequestList";
};
export function toPodCertificateRequestList(input: c.JSONValue): PodCertificateRequestList & c.ApiKind {
  const obj = c.checkObj(input);
  return {
    ...c.assertOrAddApiVersionAndKind(obj, "certificates.k8s.io/v1beta1", "PodCertificateRequestList"),
    metadata: MetaV1.toListMeta(obj.metadata),
    items: c.readList(obj.items, toPodCertificateRequest),
  }}
