export * from "./structs.ts";

// Autogenerated API file for CoordinationV1beta1
import * as c from "../../common.ts";
import * as operations from "../../operations.ts";
import * as MetaV1 from "../meta@v1/structs.ts";
import * as CoordinationV1beta1 from "./structs.ts";

export class CoordinationV1beta1Api {
  #client: c.RestClient;
  #root = "/apis/coordination.k8s.io/v1beta1/";
  constructor(client: c.RestClient) {
    this.#client = client;
  }

  namespace(name: string): CoordinationV1beta1NamespacedApi {
    return new CoordinationV1beta1NamespacedApi(this.#client, name);
  }
  myNamespace(): CoordinationV1beta1NamespacedApi {
    if (!this.#client.defaultNamespace) throw new Error("No current namespace is set");
    return new CoordinationV1beta1NamespacedApi(this.#client, this.#client.defaultNamespace);
  }

  async getLeaseCandidateListForAllNamespaces(
    opts: operations.GetListOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidateList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidateList(resp);
  }

  async watchLeaseCandidateListForAllNamespaces(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<CoordinationV1beta1.LeaseCandidate>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(CoordinationV1beta1.toLeaseCandidate, MetaV1.toStatus));
  }

}

export class CoordinationV1beta1NamespacedApi {
  #client: c.RestClient
  #root: string
  constructor(client: c.RestClient, namespace: string) {
    this.#client = client;
    this.#root = `/apis/coordination.k8s.io/v1beta1/namespaces/${namespace}/`;
  }

  async getLeaseCandidateList(
    opts: operations.GetListOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidateList> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      querystring: operations.formatGetListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidateList(resp);
  }

  async watchLeaseCandidateList(
    opts: operations.WatchListOpts = {},
  ): Promise<c.WatchEventStream<CoordinationV1beta1.LeaseCandidate>> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      expectStream: true,
      querystring: operations.formatWatchListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return resp.pipeThrough(new c.WatchEventTransformer(CoordinationV1beta1.toLeaseCandidate, MetaV1.toStatus));
  }

  async createLeaseCandidate(
    body: CoordinationV1beta1.LeaseCandidate,
    opts: operations.PutOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidate> {
    const resp = await this.#client.performRequest({
      method: "POST",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: CoordinationV1beta1.fromLeaseCandidate(body),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidate(resp);
  }

  async deleteLeaseCandidateList(
    opts: operations.DeleteListOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidateList> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}leasecandidates`,
      expectJson: true,
      querystring: operations.formatDeleteListOpts(opts),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidateList(resp);
  }

  async getLeaseCandidate(
    name: string,
    opts: operations.NoOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidate> {
    const resp = await this.#client.performRequest({
      method: "GET",
      path: `${this.#root}leasecandidates/${name}`,
      expectJson: true,
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidate(resp);
  }

  async deleteLeaseCandidate(
    name: string,
    opts: operations.DeleteOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidate | MetaV1.Status> {
    const resp = await this.#client.performRequest({
      method: "DELETE",
      path: `${this.#root}leasecandidates/${name}`,
      expectJson: true,
      querystring: operations.formatDeleteOpts(opts),
      abortSignal: opts.abortSignal,
    });
    if (c.isStatusKind(resp)) return MetaV1.toStatus(resp);
    return CoordinationV1beta1.toLeaseCandidate(resp);
  }

  async replaceLeaseCandidate(
    name: string,
    body: CoordinationV1beta1.LeaseCandidate,
    opts: operations.PutOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidate> {
    const resp = await this.#client.performRequest({
      method: "PUT",
      path: `${this.#root}leasecandidates/${name}`,
      expectJson: true,
      querystring: operations.formatPutOpts(opts),
      bodyJson: CoordinationV1beta1.fromLeaseCandidate(body),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidate(resp);
  }

  async patchLeaseCandidate(
    name: string,
    type: c.PatchType,
    body: CoordinationV1beta1.LeaseCandidate | c.JsonPatch,
    opts: operations.PatchOpts = {},
  ): Promise<CoordinationV1beta1.LeaseCandidate> {
    const resp = await this.#client.performRequest({
      method: "PATCH",
      path: `${this.#root}leasecandidates/${name}`,
      expectJson: true,
      querystring: operations.formatPatchOpts(opts),
      contentType: c.getPatchContentType(type),
      bodyJson: Array.isArray(body) ? body : CoordinationV1beta1.fromLeaseCandidate(body),
      abortSignal: opts.abortSignal,
    });
    return CoordinationV1beta1.toLeaseCandidate(resp);
  }

}
